/**
 * LPOS Custom Server
 *
 * Wraps the Next.js app with a standard Node.js HTTP(S) server,
 * attaches Socket.io, and initializes all LPOS services on startup.
 *
 * HTTPS: if localhost+1.pem / localhost+1-key.pem exist in the project root
 * (generated by `mkcert localhost 127.0.0.1`) the server starts in HTTPS mode.
 * This is required for Frame.io V4 OAuth (Adobe IMS requires a secure redirect URI).
 *
 * Start with:
 *   npm run dev    → development (HMR, verbose logging)
 *   npm start      → production
 */

import { createServer as createHttpServer }  from 'node:http';
import { createServer as createHttpsServer } from 'node:https';
import fs   from 'node:fs';
import path from 'node:path';
import { parse } from 'node:url';
import next from 'next';
import { Server as SocketIOServer } from 'socket.io';
import { initServices, stopServices, getRegistry } from './lib/services/container';

const dev      = process.env.NODE_ENV !== 'production';
const port     = parseInt(process.env.PORT ?? '3000', 10);
const hostname = process.env.HOSTNAME ?? '0.0.0.0';

// mkcert cert discovery — checks for certs with increasing SAN counts so you
// don't need to update this file when you regenerate with more hostnames/IPs.
// Looks for localhost.pem, localhost+1.pem, localhost+2.pem … up to +9
function findMkcertFiles(): { cert: string; key: string } | null {
  const suffixes = ['', '+1', '+2', '+3', '+4', '+5', '+6', '+7', '+8', '+9'];
  for (const suffix of suffixes) {
    const cert = path.join(process.cwd(), `localhost${suffix}.pem`);
    const key  = path.join(process.cwd(), `localhost${suffix}-key.pem`);
    if (fs.existsSync(cert) && fs.existsSync(key)) return { cert, key };
  }
  return null;
}
const mkcertFiles = findMkcertFiles();

async function main() {
  const nextApp = next({ dev, hostname, port });
  const handle  = nextApp.getRequestHandler();

  await nextApp.prepare();

  const requestHandler = async (
    req:  Parameters<typeof handle>[0],
    res:  Parameters<typeof handle>[1],
  ) => {
    try {
      const parsedUrl = parse(req.url ?? '/', true);
      await handle(req, res, parsedUrl);
    } catch (err) {
      console.error('[lpos] request error:', err);
      res.statusCode = 500;
      res.end('Internal server error');
    }
  };

  // ── Choose HTTP or HTTPS ────────────────────────────────────────────────────

  const httpServer = mkcertFiles
    ? createHttpsServer(
        { cert: fs.readFileSync(mkcertFiles.cert), key: fs.readFileSync(mkcertFiles.key) },
        requestHandler,
      )
    : createHttpServer(requestHandler);

  const protocol = mkcertFiles ? 'https' : 'http';

  // ── Socket.io ──────────────────────────────────────────────────────────────

  const io = new SocketIOServer(httpServer, {
    cors: { origin: '*' },
  });

  io.on('connection', (socket) => {
    socket.emit('services:status', getRegistry().list());
  });

  // ── Services ───────────────────────────────────────────────────────────────

  await initServices(io);

  // ── Graceful shutdown ──────────────────────────────────────────────────────

  for (const signal of ['SIGTERM', 'SIGINT'] as const) {
    process.on(signal, async () => {
      process.stdout.write(`\n[lpos] shutting down (${signal})...\n`);
      await stopServices();
      httpServer.close(() => {
        process.stdout.write('[lpos] goodbye\n');
        process.exit(0);
      });
    });
  }

  // ── Listen ─────────────────────────────────────────────────────────────────

  httpServer.listen(port, () => {
    const services = getRegistry()
      .list()
      .map((s) => `${s.name} (${s.status})`)
      .join('  ·  ');

    console.log('');
    console.log(`  ▲ LPOS  ${protocol}://${hostname === '0.0.0.0' ? 'localhost' : hostname}:${port}`);
    if (mkcertFiles) {
      console.log(`  🔒 cert: ${path.basename(mkcertFiles.cert)}`);
    } else {
      console.log('  ↳ Running HTTP — HTTPS handled by Tailscale.');
    }
    console.log(`  ↳ ${services}`);
    console.log('');
  });
}

main().catch((err) => {
  console.error('[lpos] failed to start:', err);
  process.exit(1);
});
