export interface MediaFolder {
  folderId: string;
  name: string;
  clientName: string;
  videoCount: number;
  totalDuration: string;
  lastUpdated: string;
  thumbnail?: string;
}

export interface VideoAsset {
  videoId: string;
  folderId: string;
  title: string;
  filename: string;
  duration: string;
  resolution: string;
  fileSize: string;
  status: 'processing' | 'ready' | 'published';
  uploadedAt: string;
  views: number;
  thumbnail?: string;
  description: string;
  tags: string[];
}

export const mediaFolders: MediaFolder[] = [
  {
    folderId: 'f1',
    name: 'Podcast Season 1',
    clientName: 'LeaderPass Media',
    videoCount: 8,
    totalDuration: '3h 42m',
    lastUpdated: '2026-03-14',
  },
  {
    folderId: 'f2',
    name: 'Executive Interviews',
    clientName: 'LeaderPass',
    videoCount: 14,
    totalDuration: '6h 18m',
    lastUpdated: '2026-03-12',
  },
  {
    folderId: 'f3',
    name: 'Neil Course',
    clientName: 'LeaderPass',
    videoCount: 21,
    totalDuration: '4h 55m',
    lastUpdated: '2026-03-10',
  },
  {
    folderId: 'f4',
    name: 'Product Demos',
    clientName: 'LeaderPass',
    videoCount: 5,
    totalDuration: '1h 12m',
    lastUpdated: '2026-03-08',
  },
  {
    folderId: 'f5',
    name: 'Onboarding Series',
    clientName: 'LeaderPass',
    videoCount: 9,
    totalDuration: '2h 04m',
    lastUpdated: '2026-02-28',
  },
  {
    folderId: 'f6',
    name: 'Social Clips',
    clientName: 'LeaderPass Media',
    videoCount: 32,
    totalDuration: '58m',
    lastUpdated: '2026-03-16',
  },
];

export const videoAssets: Record<string, VideoAsset[]> = {
  f1: [
    {
      videoId: 'v1',
      folderId: 'f1',
      title: 'Podcast 014 Final Master',
      filename: 'podcast-014-master.mp4',
      duration: '28:14',
      resolution: '1920x1080',
      fileSize: '1.2 GB',
      status: 'published',
      uploadedAt: '2026-03-14',
      views: 342,
      description: 'Final mastered export of Podcast episode 14 featuring the leadership roundtable discussion.',
      tags: ['podcast', 'episode-14', 'final'],
    },
    {
      videoId: 'v2',
      folderId: 'f1',
      title: 'Podcast 013 Final Master',
      filename: 'podcast-013-master.mp4',
      duration: '31:08',
      resolution: '1920x1080',
      fileSize: '1.4 GB',
      status: 'published',
      uploadedAt: '2026-03-07',
      views: 518,
      description: 'Final mastered export of Podcast episode 13 on entrepreneurial mindset.',
      tags: ['podcast', 'episode-13', 'final'],
    },
    {
      videoId: 'v3',
      folderId: 'f1',
      title: 'Podcast 015 Rough Cut',
      filename: 'podcast-015-rough.mp4',
      duration: '34:22',
      resolution: '1920x1080',
      fileSize: '1.6 GB',
      status: 'processing',
      uploadedAt: '2026-03-15',
      views: 0,
      description: 'Rough cut awaiting editorial review for episode 15.',
      tags: ['podcast', 'episode-15', 'rough-cut'],
    },
    {
      videoId: 'v4',
      folderId: 'f1',
      title: 'Podcast 012 Final Master',
      filename: 'podcast-012-master.mp4',
      duration: '26:45',
      resolution: '1920x1080',
      fileSize: '1.1 GB',
      status: 'published',
      uploadedAt: '2026-02-28',
      views: 891,
      description: 'Final mastered export of Podcast episode 12.',
      tags: ['podcast', 'episode-12', 'final'],
    },
  ],
  f2: [
    {
      videoId: 'v5',
      folderId: 'f2',
      title: 'Chris Carneal Interview Full Export',
      filename: 'chris-carneal-full.mp4',
      duration: '14:52',
      resolution: '3840x2160',
      fileSize: '3.8 GB',
      status: 'ready',
      uploadedAt: '2026-03-12',
      views: 78,
      description: 'Full-length interview with Chris Carneal on leadership in tech.',
      tags: ['interview', 'chris-carneal', '4k'],
    },
    {
      videoId: 'v6',
      folderId: 'f2',
      title: 'Chris Carneal Interview Cutdown',
      filename: 'chris-carneal-cut.mp4',
      duration: '06:30',
      resolution: '1920x1080',
      fileSize: '820 MB',
      status: 'published',
      uploadedAt: '2026-03-12',
      views: 214,
      description: 'Social-ready cutdown of the Chris Carneal interview.',
      tags: ['interview', 'chris-carneal', 'cutdown'],
    },
    {
      videoId: 'v7',
      folderId: 'f2',
      title: 'Sarah Mitchell Deep Dive',
      filename: 'sarah-mitchell-full.mp4',
      duration: '22:18',
      resolution: '3840x2160',
      fileSize: '5.1 GB',
      status: 'published',
      uploadedAt: '2026-03-05',
      views: 156,
      description: 'In-depth conversation with Sarah Mitchell about scaling startups.',
      tags: ['interview', 'sarah-mitchell', '4k'],
    },
  ],
  f3: [
    {
      videoId: 'v8',
      folderId: 'f3',
      title: 'Neil Entrepreneurship Module 1',
      filename: 'neil-mod1.mp4',
      duration: '09:41',
      resolution: '1920x1080',
      fileSize: '580 MB',
      status: 'published',
      uploadedAt: '2026-03-10',
      views: 1204,
      description: 'Module 1: Foundations of entrepreneurial thinking.',
      tags: ['course', 'neil', 'module-1'],
    },
    {
      videoId: 'v9',
      folderId: 'f3',
      title: 'Neil Entrepreneurship Module 2',
      filename: 'neil-mod2.mp4',
      duration: '11:05',
      resolution: '1920x1080',
      fileSize: '640 MB',
      status: 'published',
      uploadedAt: '2026-03-10',
      views: 987,
      description: 'Module 2: Market validation and opportunity assessment.',
      tags: ['course', 'neil', 'module-2'],
    },
    {
      videoId: 'v10',
      folderId: 'f3',
      title: 'Neil Entrepreneurship Module 3',
      filename: 'neil-mod3.mp4',
      duration: '12:33',
      resolution: '1920x1080',
      fileSize: '710 MB',
      status: 'ready',
      uploadedAt: '2026-03-11',
      views: 45,
      description: 'Module 3: Building your first team.',
      tags: ['course', 'neil', 'module-3'],
    },
  ],
  f4: [
    {
      videoId: 'v11',
      folderId: 'f4',
      title: 'LPOS Platform Walkthrough',
      filename: 'lpos-walkthrough.mp4',
      duration: '18:22',
      resolution: '1920x1080',
      fileSize: '920 MB',
      status: 'published',
      uploadedAt: '2026-03-08',
      views: 67,
      description: 'Full walkthrough of the LPOS dashboard for prospective clients.',
      tags: ['demo', 'lpos', 'walkthrough'],
    },
    {
      videoId: 'v12',
      folderId: 'f4',
      title: 'PassPrep Feature Demo',
      filename: 'passprep-demo.mp4',
      duration: '08:14',
      resolution: '1920x1080',
      fileSize: '480 MB',
      status: 'ready',
      uploadedAt: '2026-03-06',
      views: 23,
      description: 'Quick demo of the PassPrep course generation workflow.',
      tags: ['demo', 'passprep'],
    },
  ],
  f5: [
    {
      videoId: 'v13',
      folderId: 'f5',
      title: 'Welcome to LeaderPass',
      filename: 'welcome.mp4',
      duration: '04:15',
      resolution: '1920x1080',
      fileSize: '280 MB',
      status: 'published',
      uploadedAt: '2026-02-28',
      views: 2340,
      description: 'Introduction video for new team members and clients.',
      tags: ['onboarding', 'welcome'],
    },
  ],
  f6: [
    {
      videoId: 'v14',
      folderId: 'f6',
      title: 'Leadership Tip #42',
      filename: 'tip-42.mp4',
      duration: '00:58',
      resolution: '1080x1920',
      fileSize: '45 MB',
      status: 'published',
      uploadedAt: '2026-03-16',
      views: 4521,
      description: 'Short-form leadership tip for social distribution.',
      tags: ['social', 'tip', 'vertical'],
    },
    {
      videoId: 'v15',
      folderId: 'f6',
      title: 'Leadership Tip #41',
      filename: 'tip-41.mp4',
      duration: '01:12',
      resolution: '1080x1920',
      fileSize: '52 MB',
      status: 'published',
      uploadedAt: '2026-03-14',
      views: 3892,
      description: 'Short-form leadership tip for social distribution.',
      tags: ['social', 'tip', 'vertical'],
    },
  ],
};
